# Generated by Django 2.2 on 2020-05-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '培训机构', 'verbose_name_plural': '培训机构'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '老师', 'verbose_name_plural': '老师'},
        ),
    ]
